eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

spring:
  application:
    name: auth-server
  redis:
    database: 0
    host: localhost
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
    port: 6379

server:
  port: 6001

management:
  endpoint:
    health:
      enabled: true